### ISSUE TITLE
Sign Up Error

### ISSUE THREAD

**Issue by Jeffchiucp** [Broaden-io/Broaden-io-client#102]
Here's a suggestion for the sign up page:

with the toast message when they cannot sign up for new account.   The minimum length requirement for the username has to be at least 5 character long...
So I think it would be good feature request for our users to get more specific kind of error message, right now, they only see that cannot login
![suckyerror](https://user-images.githubusercontent.com/10523517/42490720-9cc59128-83c6-11e8-8483-6a192ea7ec4d.png)

https://github.com/Broaden-io/Broaden-io-client/blob/b955570d1ff12eaff2c7034d1b2746f670b38d3f/src/components/Alert.js#L16

**Comment by tlambrou** [comment]
You should check out the input component that I made for Mission Consultants.  You can turn on and off whether the field displays as valid or not.  We can also use this to disable the login button until the input fields are valid.

**Comment by Jeffchiucp** [comment]
closed this ticket #103 #105
